name:                summy
version:             0.1.0.0
github:              "autonomousorganization/summy"
license:             BSD3

extra-source-files:
- README.md
- CHANGELOG.md

description: Summarize Core Lightning status with rpc calls and forward logs

dependencies:
- base >= 4.7 && < 5
- clplug
- aeson
- mtl
- text
- fmt
- format-numbers
- time 
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  summy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

